name: 'Build tests'
description: 'Build application'
runs:
  using: "composite"
  steps:
    - name: Remove existing build environment
      shell: bash
      run: |
        cmake -E remove -f build

    - name: Create new build environment
      shell: bash
      run: |
        cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc

    - name: Compile
      shell: bash
      run: |
        cmake --build build
